### ISSUE TITLE
Check off finished tasks

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-user-stories#2]
## Value Proposition

**As a** User
**I need** checkboxes for each task
**to be able to** check it off as done.

## Description

<img width="200" alt="UserStory02" src="https://user-images.githubusercontent.com/102236373/179225705-918a5031-e811-42df-bd42-923dfc5d417a.png">

## Acceptance Criteria

- [ ] Each task needs its own checkbox
- [ ] The checkboxes are unchecked by default
- [ ] Once the user has completed a task he can check it off

## Tasks

(for developers team)

- [ ] Create feature branch 
- [ ] Add checkbox to daily task component

**Comment by yvonneadam** [comment]
Clear and specific enough in my eyes. Good one!
