### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-user-stories#4]
## Value Proposition

**As a** User
**I need**  a Homepage
**to be able to** see my current tasks.

## Description

<img width="226" alt="UserStory_04" src="https://user-images.githubusercontent.com/102236373/179480051-e9efb0f0-d2c4-4ff7-a2a9-7ad46f1d5757.png">

## Acceptance Criteria

- [ ] I have a home page that displays the card component "täglich".
- [ ] The page title „Aktuelle Aufgaben“ is displayed above the "täglich" component.

## Tasks

(for developers team)

- [ ] create HomePage.js
- [ ] add "täglich" tasks as a card component to the homepage
- [ ] Global Styles
- [ ] Add to Storybook
- [ ] Write tests

**Comment by PReichetanz** [comment]
Hi Alice,

looks good! The only thing is that you don't need to add Global Styles to every story, because they were already set in the very first story. Even if you adjust them a little bit, that's not really a task ;)
