### ISSUE TITLE
List of tasks for the current day

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-user-stories#5]
## Value Proposition

1. **As a** User
**I need** a list of tasks
**to be able to** check it off as done.

2. **As a** Developer
**I need** data (tasks)
**to be able to** fill the database.

## Description
User:
<img alt="UserStory_05" src="https://user-images.githubusercontent.com/102236373/179548727-a344b321-13e3-4719-afc5-1da6a5621ffd.png">

Developer:
<img alt="UserStory_05-TemplateData" src="https://user-images.githubusercontent.com/102236373/179545595-89ffae3e-a916-4184-86fd-183d1f7b1ebd.png">

## Acceptance Criteria

- [ ] A second card with the *weekly tasks*, displayed under the first card of *daily tasks*.
- [ ] Only the daily (täglich) and the weekly (e.g. Montags) recurring tasks for the current day are displayed.
- [ ] The structure of the second card is the same as the first card (title, description, checkable list of tasks).
- [ ] The homepage is scrollable.
- [ ] On weekends (samstags & sonntags ), instead of the tasks, a funny picture is displayed as a reward for the completed tasks.

## Tasks

(for developers team)

- [ ] Fill db with template data.
- [ ] Add the weekly tasks for the current day to homepage.
- [ ] Add weekend card to Storybook.
- [ ] Write tests.

**Comment by anresa** [comment]
You did a great job in summing up a complex feature! To improve it even more, I have some feedback that I hope will be helpful. ☀️

The Value Proposition isn't quite clear to me in its phrasing. Maybe write something like "...to be able to check each task off as done." 

Where are the funny pictures coming from? Are you using a database for them as well? If not, I'd create a separate task for that function.

**Comment by chris-yooo** [comment]
looks great to me

maybe add to acceptence crit. that you implement a static picture for sat. and sun. :) then you finished the goal from anna.

and for the developer description you can write down the insert for Monday Thuesday etc... direkt here in the markdown without the big second picture.

<3

**Comment by actyvystom** [comment]
Hi Alice, 
I like the level of detail of your user stor(ies) :)
But keep in mind that a user story should be short and as precise as possible, so you should reflect only one persona per user story. I suggest stripping the developer story to a new user story and then you are good to go with both of them ;)
The level of detail for your template data is really extended but if you feel comfortable with keeping the template data inside your (developer) user story, this would also be fine.

**Comment by chris-yooo** [comment]
here same you added a list for the "db" datas

and the splited version between developer and user view are exciting!

maybe one cool thing is the random giphy from this little tool: https://www.npmjs.com/package/giph

<3 it
