### ISSUE TITLE
(user) List of tasks for the current day

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-user-stories#6]
## Value Proposition

**As a** User
**I need** a list of tasks
**to be able to** check each task off as done.

## Description
<img alt="UserStory_05" src="https://user-images.githubusercontent.com/102236373/179548727-a344b321-13e3-4719-afc5-1da6a5621ffd.png">

<img alt="UserStory_05-weekend" src="https://user-images.githubusercontent.com/102236373/179742041-1a023ffb-6de7-48e4-800c-bb95fcd07866.png">

## Acceptance Criteria

- [ ] A second card with the *weekly tasks*, displayed under the first card of *daily tasks*.
- [ ] Only the daily (täglich) and the weekly (e.g. Montags) recurring tasks for the current day are displayed.
- [ ] The structure of the second card is the same as the first card (title, description, checkable list of tasks).
- [ ] On weekends (samstags & sonntags ), instead of the tasks, a funny picture is displayed as a reward for the completed tasks.
- [ ] The homepage is scrollable.

## Tasks

(for developers team)

- [ ] Add the weekly tasks for the current day to homepage.
- [ ] Add weekend card to Storybook.
- [ ] Add demo picture *funny dog* for the weekend card.
- [ ] Write tests.

**Comment by chris-yooo** [comment]
i find the split version between developer and user view cooler and clearer. Although from the coaches was said you can also see the developer view and or other view :)

:D

<3 it
