### ISSUE TITLE
Form to add new tasks

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-user-stories#7]
## Value Proposition

**As a** User
**I need** an input form
**to be able to** to add new tasks to my lists.

## Description
![UserStory_07-01](https://user-images.githubusercontent.com/102236373/179837254-470ee2dc-9cea-48bc-a888-e77b2b7b1cd9.png)
![UserStory_07-02](https://user-images.githubusercontent.com/102236373/179837267-bce10813-4322-4350-b915-d106f5fbcdce.png)

## Acceptance Criteria

- [ ] A button with a plus sign will be displayed at the right end of the screen. (Screen 1)
- [ ] The "+" button links to a form page (Screen 2)
- [ ] Form page has a title "Aufgaben hinzufügen" (Screen 3)
- [ ] Form has two inputs, both are required.
- [ ] The first field is labeled "Aufgabe" and is a text input.
- [ ] The second field is labeled "Kategorie" and is a dropdown menu with the options "täglich, Montags, Dienstags, Mittwochs, Donnerstags, Freitags". 
- [ ] The options are highlighted when hovering over them. 
- [ ] Only one option may be selected. 
- [ ] There are two buttons below the input fields.
- [ ] The left button "zurück" links back to screen 1 (homepage).
- [ ] The right button "abschicken" submits the form.
- [ ] When clicking on "abschicken" without valid input, an error message is displayed. (Screen 4)
- [ ] When the form is submitted, screen 3 (Home/Show Current Tasks) will be displayed with the new task at the end of the selected list.

## Tasks

(for developers team)

- [ ] Create component/AddTask
- [ ] Create component/Form
- [ ] Add "+" Button and Form to Storybook.
- [ ] Write tests.

**Comment by PReichetanz** [comment]
Hi Alice,

a really good your user story! 🎉

💬 I have only one tiny issue:

## Acceptance Criteria
- "Form page has a title "Aufgaben hinzufügen" (Screen 3)" - I think it's screen 2.

**Comment by alicie232** [comment]
@PReichetanz ooops thank you! 🙈❤️

**Comment by chris-yooo** [comment]
ok your "Kategorie" drop down are you weekly days ... ok seems to be legit - great idea.

after the typo error of paul i think you get a green hook :D

chris
